sudo: required
dist: trusty
language: node_js
git:
  depth: 10
node_js:
  - "6"
before_install:
  # Remove ./node_modules/.bin from PATH so node-which doesn't replace Unix which and cause RVM to barf. See https://github.com/travis-ci/travis-ci/issues/5092
  - export PATH=$(python -c 'from sys import argv;from collections import OrderedDict as od;print(":".join(od((p,None) for p in argv[1].split(":") if p.startswith("/")).keys()))' "$PATH")
  - rvm install 2.2
  - rvm use 2.2 --fuzzy
install:
  - bundle install --deployment --jobs=1
  - npm install
  - yarn
# Undo `_JAVA_OPTIONS` environment variable;
# see https://github.com/travis-ci/travis-ci/issues/8408
before_script:
  - _JAVA_OPTIONS=
cache:
  directories:
    - node_modules
    - vendor/bundle
script:
  - npm run build-intern
  - npm run dist-intern
