branches:
  only:
    - master
    - dev
    - dev-travis
    - documentation
sudo: required
dist: trusty
language: node_js
git:
  depth: 10
node_js:
  - "6"
before_install:
  # Remove ./node_modules/.bin from PATH so node-which doesn't replace Unix which and cause RVM to barf. See https://github.com/travis-ci/travis-ci/issues/5092
  - export PATH=$(python -c 'from sys import argv;from collections import OrderedDict as od;print(":".join(od((p,None) for p in argv[1].split(":") if p.startswith("/")).keys()))' "$PATH")
  - rvm install 2.5.1
  - rvm use 2.5.1 --fuzzy
install:
  - bundle install --deployment --jobs=1
  - npm install
  - yarn
# Undo `_JAVA_OPTIONS` environment variable;
# see https://github.com/travis-ci/travis-ci/issues/8408
before_script:
  - _JAVA_OPTIONS=
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')}
  - git tag $TRAVIS_TAG
cache:
  directories:
    - node_modules
    - vendor/bundle
script:
  - mkdir documentation

  # Intern / metier
  - npm run build-intern
  - npm run dist-intern
  - npm run docs-compile-intern
  - mv _gh_pages documentation/intern
  - tar -zcf bootstrap-sncf-intern_${TRAVIS_TAG}.snapshot.tar.gz dist/
  - zip -r documentation/intern/dist.zip dist/
  - rm -rf dist

  # Extern / communication
  - npm run build-extern
  - npm run dist-extern
  - npm run docs-compile-extern
  - mv _gh_pages documentation/extern
  - tar -zcf bootstrap-sncf-extern_${TRAVIS_TAG}.snapshot.tar.gz dist/
  - zip -r documentation/extern/dist.zip dist/
deploy:
  provider: releases
  skip_cleanup: true
  prerelease: true
  api-key: $GITHUB_OAUTH
  file:
    - "bootstrap-sncf-intern_${TRAVIS_TAG}.snapshot.tar.gz"
    - "bootstrap-sncf-extern_${TRAVIS_TAG}.snapshot.tar.gz"
  on:
    branch: master
deploy:
  skip-cleanup: true
  provider: script
  script: ./scripts/pushdocs.sh
  on:
    branch: dev-travis
