sudo: required
dist: trusty
language: node_js
git:
  depth: 10
node_js:
  - "6"
before_install:
  # Remove ./node_modules/.bin from PATH so node-which doesn't replace Unix which and cause RVM to barf. See https://github.com/travis-ci/travis-ci/issues/5092
  - export PATH=$(python -c 'from sys import argv;from collections import OrderedDict as od;print(":".join(od((p,None) for p in argv[1].split(":") if p.startswith("/")).keys()))' "$PATH")
  - rvm install 2.5.1
  - rvm use 2.5.1 --fuzzy
install:
  - bundle install --deployment --jobs=1
  - npm install
  - yarn
# Undo `_JAVA_OPTIONS` environment variable;
# see https://github.com/travis-ci/travis-ci/issues/8408
before_script:
  - _JAVA_OPTIONS=
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
cache:
  directories:
    - node_modules
    - vendor/bundle
script:
  - npm run build-intern
  - npm run dist-intern
  - tar -zcf bootstrap-sncf-intern_${TRAVIS_TAG}.snapshot.tar.gz dist/
  - npm run build-extern
  - npm run dist-extern
  - tar -zcf bootstrap-sncf-extern_${TRAVIS_TAG}.snapshot.tar.gz dist/
before_deploy:
  - export RELEASE_TAR_GZ_FILE=$(ls bootstrap-sncf*.snapshot.tar.gz)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
deploy:
  provider: releases
  skip_cleanup: true
  api-key: $GITHUB_OAUTH
  file: "${RELEASE_TAR_GZ}"
  file_glob: true
  

