# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Server
source:         ./templates
destination:    ./_gh_pages
host:           0.0.0.0
port:           9001
baseurl:        ""
url:            "https://designmetier-bootstrap.sncf.fr"
urlother:       "https://design-bootstrap.sncf.fr"
encoding:       UTF-8
exclude:
  - extern
  - docs-extern

keep_files:
  - assets
  - bootstrap-sncf.js
  - bootstrap-sncf.js.map
  - bootstrap-sncf.css
  - bootstrap-sncf.css.map
  - bootstrap-sncf.darkmode.css
  - bootstrap-sncf.darkmode.css.map
  - vendor

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

# Social
title:              Bootstrap Métier
titleother:         Bootstrap Communication
description:        ""
twitter:            getbootstrap
authors:            "SNCF Fab Design, Mark Otto, Jacob Thornton, and Bootstrap contributors"
social_image_path:  /assets/brand/bootstrap-social.png
social_logo_path:   /assets/brand/bootstrap-social-logo.png

# Custom variables
current_version:      4.3.1
current_ruby_version: 4.0.0
docs_version:         4.3
sncf_version:         3
repo:                 "https://github.com/SNCFdevelopers/bootstrap-sncf"
slack:                "https://bootstrap-slack.herokuapp.com"
blog:                 "https://www.digital.sncf.com"
expo:                 "https://www.digital.sncf.com"
jobs:                 "https://www.digital.sncf.com"
themes:               "https://themes.getbootstrap.com"
doc_theme:            "intern"
flavor:               "metier"
name:                 "DESIGN MÉTIER"

download:
  source:           "https://github.com/SNCFdevelopers/bootstrap-sncf/archive/master.zip"
  dist:             "/dist.zip"

toc:
  min_level:        2
  max_level:        4
