languageCode:           "en"
title:                  "Bootstrap Métier"
BaseURL:                ""
enableInlineShortcodes: true

pygmentsUseClasses:     true
# you can use ```lang if you want too
pygmentsCodeFences:     true

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

blackfriday:
  fractions:            false

publishDir:             "_gh_pages"
archetypeDir:           "site/archetypes"
assetDir:               "_gh_pages/assets"
contentDir:             "site/content"
dataDir:                "site/data"
layoutDir:              "site/layouts"
staticDir:              "_gh_pages"

permalinks:
  intern:               "/docs"

ignoreFiles:            "extern"

params:
  description:          "SNCF Design's system integration, based on Bootstrap, the most popular HTML, CSS, and JS library in the world."
  authors:              "SNCF Fab Design, Mark Otto, Jacob Thornton, and Bootstrap contributors"
  social_image_path:    /docs/4.3/assets/brand/bootstrap-social.png
  social_logo_path:     /docs/4.3/assets/brand/bootstrap-social-logo.png

  current_version:      "4.3.1"
  docs_version:         "4.3"
  sncf_version:         "2"
  repo:                 "https://github.com/SNCFdevelopers/bootstrap-sncf"
  doc_flavour:          "intern"
  doc_theme:            "metier"
  name:                 "DESIGN MÉTIER"
  url:                  "https://designmetier-bootstrap.sncf.fr"
  urlother:             "https://design-bootstrap.sncf.fr"
  titleother:           "Bootstrap Communication"

  download:
    source:             "https://github.com/SNCFdevelopers/bootstrap-sncf/archive/master.zip"
