languages:
  en:
    languageName: English
    description:  "SNCF Design's system integration, based on Bootstrap, the most popular HTML, CSS, and JS library in the world."
    weight: 1
  fr:
    languageName: Français
    description:  "Intégration du Design System SNCF, basé sur Bootstrap, la librairie HTML, CSS et JS la plus populaire du monde."
    weight: 2

BaseURL:                ""
enableInlineShortcodes: true

pygmentsUseClasses:     true
# you can use ```lang if you want too
pygmentsCodeFences:     true

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

blackfriday:
  fractions:            false

publishDir:             "_gh_pages"
archetypeDir:           "site/archetypes"
assetDir:               "_gh_pages/assets"
contentDir:             "site/content"
dataDir:                "site/data"
layoutDir:              "site/layouts"
i18nDir:                "site/i18n"
staticDir:              "_gh_pages"

DefaultContentLanguage: en

params:
  authors:              "SNCF Fab Design, Mark Otto, Jacob Thornton, and Bootstrap contributors"
  social_image_path:    /docs/4.3/assets/brand/bootstrap-social.png
  social_logo_path:     /docs/4.3/assets/brand/bootstrap-social-logo.png

  current_version:      "4.3.1"
  docs_version:         "4.3"
  sncf_version:         "3"
  repo:                 "https://github.com/SNCFdevelopers/bootstrap-sncf"
  url_metier:           "https://designmetier-bootstrap.sncf.fr"
  url_communication:    "https://design-bootstrap.sncf.fr"

  download:
    source:             "https://github.com/SNCFdevelopers/bootstrap-sncf/archive/master.zip"
