import 'bootstrap'
import './docs/application.js'
import './docs/ie-emulation-modes-warning.js'
import './docs/stop-propagation.js'
// import './docs/pwa.js'
import './docs/darkmode.js'
import './docs/hidesource.js'
import './docs/language-switch.js'
